services:
  database:
      container_name: cn24-dev-database
      image: postgres:16
      ports:
        - "5432:5432"
      restart: unless-stopped
      environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=cn24
      volumes:
        - dev_database:/var/lib/postgresql/data

volumes:
  dev_database: